export { animationCommand } from "./animation"
export { clearCommand } from "./clear"
export { flowersCommand, plantFlowers } from "./flowers"
export { fontCommand } from "./font"
export { helloCommand } from "./hello"
export { helpCommand } from "./help"
export { langCommand } from "./lang"
export { testCommand } from "./test"
export { themeCommand } from "./theme"
